# Problem solving

## Easy

### Create a 2D NumPy array with 3 rows and 4 columns, containing random integers between 1 and 10. Then, calculate the sum of all elements in the array.


In [3]:
import numpy as np
arr=np.random.randint(1,11,(3,4))
print(arr)
sum=0
for i in range(0,3):
    for j in range(0,4):
        sum=sum+arr[i,j]          # cautious about the range and for loop syntax
print(sum)
#help(np.random.randint)

[[ 2 10  7  1]
 [ 1  3  4  8]
 [ 2  1  7  2]]
48


### Write a NumPy function to swap the columns of a given 2D array.

In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.zeros((3,1),dtype=int)

print(a)
print(b)
c=np.concatenate((a,b),1)
print(c)
for i in range(0,3):
    c[i,3]=c[i,2]
for i in range(0,3):
    c[i,2]=c[i,1]
for i in range(0,3):
    c[i,1]=c[i,3]
d=np.delete(c,3,axis=1)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0]
 [0]
 [0]]
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
[[1 3 2]
 [4 6 5]
 [7 9 8]]


### Given two 1D NumPy arrays, a and b, containing integers, create a new array c that contains the elements of a multiplied by the corresponding elements of b.


In [9]:
import numpy as np
a=np.random.randint(1,10,5)
b=np.random.randint(1,10,5)
print(a,'\n',b)
print()
c=a*b
print(c)

[2 7 3 1 3] 
 [2 5 8 5 9]

[ 4 35 24  5 27]


## Intermediate

### Create a 3D NumPy array with shape (2, 3, 4), containing random integers between 1 and 10. Then, reshape the array to have shape (3, 2, 4).


In [ ]:
import numpy as np
a=np.random.randint(1,10,(2,3,4))
print(a)
a.reshape((3,2,4))

### Write a NumPy function to remove the duplicate rows from a given 2D array.


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[1,2,3]])
len(a)
print(a.shape[0])
print(a.shape[1])
print(np.array_equal(a[1],a[3]))
def clean(x):
    for i in range(0,x.shape[0]):                                # row iteration
        for j in range(i+1,x.shape[0]):                          # comparing rows
            if np.array_equal(x[i],x[j]):                        # checking if they are equal or not
                x=np.delete(x,j,axis=0)
    print(x)
clean(a) 

### Given a 2D NumPy array, arr, containing integers, create a new array that contains the cumulative sum of each row in arr.


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[1,2,3]])
print(a)
sum_array = np.zeros((a.shape[0],1),dtype=int)
sum_array
for i in range(0,a.shape[0]):                         #row iteration
    for j in range(0,a.shape[1]):
        sum_array[i,0]=sum_array[i,0]+a[i, j]
sum_array

### Create a 2D NumPy array with 4 rows and 5 columns, containing random integers between 1 and 10. Then, extract the elements of the array that are greater than 5.


In [ ]:
import numpy as np
a= np.random.randint(1,10,(4,5))
a
b=[]
for i in range(0,a.shape[0]):
    for j in range(0,a.shape[1]):
        if (a[i,j]>5):
            b.append(a[i,j])
print(np.array(b))

### Write a NumPy function to extract the diagonal elements of a given 2D array.

In [ ]:
import numpy as np
a=np.random.randint(1,10,(5,4))
print(a)
print()
b=[]
def diag(x):
    for i in range(0,min(x.shape[0],x.shape[1])):       # iterating along the column/row whichever is minimum
        b.append(a[i,i])
    print(b)
diag(a)

### Given a 3D NumPy array, arr, containing integers, create a new array that contains the elements of arr sliced along the second axis.

In [ ]:
import numpy as np
a=np.random.randint(1,10,(2,3,4))
print(a)
print()
b=[]
for i in range(0,a.shape[1]):            # clarify the logic of slicing along sense
    b.append(a[:,i,:])
print(b)

### Create a 1D NumPy array containing random integers between 1 and 10. Then, calculate the mean, median, and standard deviation of the array.

In [ ]:
import numpy as np
x=np.random.randint(1,10,10)
print('x = ',x)
print('mean = ',np.mean(x))
print('median = ',np.median(x))
print('sd = ',np.round(np.sqrt(np.var(x)),4))

###  Write a NumPy function to calculate the dot product of two given 1D arrays.

In [ ]:
import numpy as np
a=np.array([1,2,4])
b=np.array([2,5,9])
np.dot(a,b)

## Hard

### Given a 2D NumPy array, arr, containing integers, create a new array that contains the matrix product of arr with its transpose.


In [ ]:
import numpy as np
arr=np.random.randint(1,10,(3,4))
arr=np.matrix(arr)
print(arr)
print()
print(np.transpose(arr))
print()
print(arr*np.transpose(arr))

### Create a NumPy array with a custom data type that contains two fields: name (a string of length 10) and age (an integer).


In [ ]:
import numpy as np
x=np.array([10,35,40],dtype=int)
y=np.array(['son','mother','father'])
family=np.array({'Name':['son','mother','father'],'age':[10,35,40]})
family

In [ ]:
np.transpose(np.array([('A',2),('B',4),('C',6)],dtype=np.dtype([('name','U8'),("age","i8")])))

###  Write a NumPy function to perform a Fourier transform on a given 1D array.

### Given a 2D NumPy array, arr, containing integers, create a new array that contains the eigenvalues and eigenvectors of arr.

In [ ]:
import numpy as np
x=np.random.randint(1,10,(3,3))
print(x)
y=np.linalg.eig(x)
print('Eigen Values',y[0])
print('Eigen Vectors',np.array(y[1]))